window.version='1.6';
window.changelog={	
    '2020年06月12日':{
    'version':'1.6',
    'info':'新增欢乐音效、新增并修改武将【寰宇星城】<li>修改武将【水乎】【橙续缘】、【雪碧】。当前扩展版本已升版至为1.6',
    'players':["wwyj_huanyuxingcheng","wwyj_shuihu","wwyj_chengxuyuan","wwyj_xuebi"],
    'cards':[],
  },
  '2020年05月26日':{
    'version':'1.5',
    'info':'调整个别素材，删除部分没用到的配音文件<li>修改武将【凉茶】、【提笼架鸟】、【烟雨墨染】。当前扩展版本已升版至为1.5',
    'players':["wwyj_liangchas","wwyj_tilongjianiao","wwyj_yanyumoran"],
    'cards':[],
  },
  '2020年05月':{
    'version':'1.4',
    'info':'美化本扩展的界面并增加查看更新日志功能和反馈BUG、提建议的通道<li>新增武将：松岛枫桂花',
    'players':["wwyj_guihua"],
    'cards':[],
  },
  '2020年04月':{
    'version':'1.3',
    'info':'新增浅觞、咸鱼、神奈、一瞬间遗忘、流沙等，移植BOSS凉茶（天神降临模式），修改雪碧，平衡部分武将的强度等<li>将本扩展的武将的势力改为“杀”势力，并适配“十周年UI”扩展，补充阵亡配音，新增武将前缀、武将聊天、随机武将、英灵附魂等模式',
    'players':["wwyj_qianshangs","wwyj_yitiaoxianyu","wwyj_shennais","wwyj_yiwangs","wwyj_liushas","wwyj_liangchax"],
    'cards':[],
  },
  '2020年03月':{
    'version':'1.2',
    'info':'收录兵乐特效、击杀特效和新增图鉴模式、背景图片、背景音乐等<li>新增以下武将',
    'players':["wwyj_remaliao","wwyj_shenzuo","wwyj_xuebi","wwyj_lengyus","wwyj_zhugejun","wwyj_zhaonies"],
    'cards':[],
  },
  '2020年02月-2020年03月':{
    'version':'1.1',
    'info':'修复bug，扩展加入联机框架，将武将进行分类，补充武将简介，添加配音函数，扩展改名为《文武英杰》<li>添加以下武将',
    'players':["wwyj_jiguangs","wwyj_danwuyunxi","wwyj_xingyunnvshen","wwyj_feicheng","wwyj_wali","wwyj_yanyumoran"],
    'cards':[],
  },
  '2020年01月-2020年02月':{
    'version':'1.0',
    'info':'构思并开始制作扩展，此时扩展名为《无名风云录》<li>制作以下武将',
    'players':["wwyj_shuihu","wwyj_chengxuyuan","wwyj_pipi","wwyj_Sukincen","wwyj_wzszhaoyun","wwyj_lunhuizhong","wwyj_ziyage","wwyj_kanpoyiqie","wwyj_daxiongxiaimao","wwyj_liangchas","wwyj_kelejiabing","wwyj_huijin","wwyj_maliao","wwyj_taishangdaniu","wwyj_shijian"],
    'cards':[],
  },
}