extension["新•界限突破"]={
	intro:"◇《三国杀十周年》新服界限突破扩展。<br>◇原界限突破包中已拥有的武将会直接替换原技能，新的界限突破武将会以扩展武将形式出现。所有包含「新版替换」的标准包武将都会还原为原版。",
	author:"苏婆玛丽奥",
	netdisk:"",
	forum:"",
	version:"1.0",
	files:["re_huaxiong.jpg","extension.js","re_diaochan.jpg","re_huangyueyingx.jpg","re_sunquan.jpg",
		"re_sunshangxiang.jpg","re_zhenji.jpg","re_zhugeliang.jpg","new_drlt_jueyan1.mp3",
		"new_drlt_jueyan2.mp3"],
	size:"147KB"
};